---
layout: cv
title: Roy Morin's Resume 
---
# Roy Morin



<div id="webaddress">
| <a href="https://www.linkedin.com/in/roy-morin">My LinkedIn page</a>
</div>


## Education

__Western Wyoming Community College__
`Rock Springs, Wyoming, Fall 2020 - Spring 2023`

- Associates Degree in Mathematics

__Brigham Yound Universiry - Idaho__
`Rexburg, Idaho, Fall 2023 - Current`

- Pursuing Statistics Bachelor's


## Work Experience

__Statistics__

`Significant assignments as a BYU-I Student (2023 - Current)`

- Worked with a real client to research consumer habits using R.

- Created machine learning models with Wordle data with R.


__City of Green River Parks and Recreation Department__

`Seasonal Operations Assistent (May - August of 2021 - 2023, Green River, Wyoming)`

- Setting and collecting mosquito traps, counting dead mosquitos, and checking for species that can carry West Nile Virus. Done on my own. 

- Prepared baseball, softball, football, and soccer fields. Done with a team. 

- Mowing with walk behind and riding mowers and tractors, trimming, weed whacking city property, and driving a fog truck to spray mosquitos. Done with a team and on my own. 

- Assisted to training new employees. 

__Green River Star__

`Newpaper Deliverer (2013 - 2017, Green River, Wyoming)`

- Pick up newspapers, fold them, and deliver them in a timely manner. 

## Tools

`Experience`

- Working with a team (In sports and school projects)

- Operating Machinery

- Teaching a class

- Mentoring incoming Freshman in High School

- Coding with Python

- Coding with R


## Awards

`2020`
Student vs Staff Charity Basketball Game MVP



<!-- ### Footer

Last updated: May 2013 -->